locals {

  # This is a map of Azure region names to short names used in resource names
  short_location_names = {
    "us-east"          = "ue"
    "us-east-2"        = "ue2"
    "us-central"       = "uc"
    "us-north-central" = "unc"
    "us-south-central" = "usc"
    "us-west-central"  = "uwc"
    "us-west"          = "uw"
    "us-west-2"        = "uw2"
    "us-west-3"        = "uw3"
    "can-east"         = "cae"
    "can-central"      = "cac"
    "bra-south"        = "brs"
    "bra-south-east"   = "brse" # Brazil Southeast
    "eu-north"         = "eun"
    "eu-west"          = "euw"
    "fr-central"       = "frc"
    "fr-south"         = "frs"
    "uk-west"          = "ukw"
    "uk-south"         = "uks"
    "ger-central"      = "gce"
    "ger-north-east"   = "gne"
    "ger-north"        = "gno"
    "ger-west-central" = "gwc"
    "swedencentral"    = "sdc"
    "swedensouth"      = "sds"
    "swz-north"        = "swn"
    "swz-west"         = "sww"
    "norw-east"        = "noe"
    "norw-west"        = "now"
    "asia-south-east"  = "ase"
    "asia-east"        = "ae"
    "aus-east"         = "aue"
    "aus-south-east"   = "ause"
    "aus-central"      = "auc"
    "aus-central-2"    = "auc2"
    "cn-east"          = "cne"
    "cn-north"         = "cnn"
    "cn-east-2"        = "cne2"
    "cn-north-2"       = "cnn2"
    "cn-east-3"        = "cne3"
    "cn-north-3"       = "cnn3"
    "ind-central"      = "inc"
    "ind-west"         = "inw"
    "ind-south"        = "ins"
    "jap-east"         = "jpe"
    "jap-west"         = "jpw"
    "kor-central"      = "krc"
    "kor-south"        = "krs"
    "saf-west"         = "saw"
    "saf-north"        = "san"
    "uae-central"      = "uaec"
    "uae-north"        = "uaen"
  }
}
